# Define a imagem base do Node.js
FROM node:16-alpine AS builder

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia o arquivo package.json e o arquivo yarn.lock para o diretório de trabalho
COPY package.json yarn.lock ./

# Instala as dependências do projeto
RUN yarn install

# Copia todos os arquivos do projeto para o diretório de trabalho
COPY . .



# Define a imagem base do servidor web
FROM nginx:alpine

# Remove os arquivos de configuração padrão do Nginx
RUN rm -rf /etc/nginx/conf.d/*

# Copia o arquivo de configuração do Nginx para o diretório de configuração do Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copia os arquivos gerados pelo Vite para o diretório do servidor web
COPY --from=builder /app/dist /usr/share/nginx/html

# Expõe a porta 80 para que a aplicação possa ser acessada através do navegador
EXPOSE 5173

# Define o comando de inicialização do container
CMD ["nginx", "-g", "daemon off;"]
