name: GCP

on:
    push:
        branches: [main]

jobs:
    deploy:
        name: Deploy API
        runs-on: ubuntu-latest
        env:
            IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/api-gaapo:latest
        steps:
            # Git checkout
            - name: Checkout
              uses: actions/checkout@v2

            - name: Navigate to Docker folder
              run: cd src/api/api/
            # Login to GCP
            - uses: google-github-actions/setup-gcloud@v0.2.0
              with:
                  service_account_key: ${{ secrets.GCP_CREDENTIALS }}
                  project_id: ${{ secrets.GCP_PROJECT_ID }}

            - name: Onde ta o projeto
              run: cd src/api/api/ && pwd
            
            - name: lista arquivo
              run: cd src/api/api/ && ls

            # gcloud configure docker
            - name: Configure Docker
              run: cd src/api/api/ && gcloud auth configure-docker --quiet

            # build image
            - name: Build Docker image
              run: cd src/api/api/ && docker build --no-cache -t $IMAGE_NAME .

            # push image to registry
            - name: Push Docker image
              run: cd src/api/api/ && docker push $IMAGE_NAME

            # deploy image
            - name: Deploy Docker image
              run: cd src/api/api/ && gcloud run deploy api-gaapo --image $IMAGE_NAME --max-instances 5 --project ${{ secrets.GCP_PROJECT_ID }} --platform managed --region us-west1 --allow-unauthenticated
